Q1

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
reversed_arr=arr[::-1]
print("reversed_array:",reversed_arr)

reversed_array: [5 4 3 2 1]


In [4]:
array1=np.array([[1,2],[3,4]])
print(array1.flatten())

[1 2 3 4]


In [5]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(a1, a2))

True


In [11]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
val = np.bincount(x).argmax()
print("Most frequent:", val, "Indices:", np.where(x == val))
y = np.array([1,1,1,2,3,4,2,4,3,3,])
val1 = np.bincount(x).argmax()
print("Most frequent:", val1, "Indices:", np.where(y == val1))


Most frequent: 1 Indices: (array([0, 5, 7, 8, 9]),)
Most frequent: 1 Indices: (array([0, 1, 2]),)


In [9]:
gfg=np.matrix([[4,1,9],[12,3,1],[4,5,6]])
print(gfg.sum())
print(gfg.sum(axis=1))
print(gfg.sum(axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [10]:
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print(np.trace(n_array))
print(np.linalg.eig(n_array))
print(np.linalg.inv(n_array))
print(np.linalg.det(n_array))

176
EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [12]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print(np.dot(p, q))
print(np.cov(p, q))

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [13]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x, y))
print(np.outer(x, y))
print(np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2))

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2

In [20]:
arr=np.array([[1,-2,3],[-4,5,-6]])
print(np.abs(arr))
print(np.percentile(arr,25,axis=0))
print(np.percentile(arr,50,axis=0))
print(np.percentile(arr,75,axis=0))
print(np.percentile(arr,25,axis=1))
print(np.percentile(arr,50,axis=1))
print(np.percentile(arr,75,axis=1))
print(np.mean(arr,axis=0))
print(np.median(arr,axis=0))
print(np.std(arr,axis=0))
print(np.mean(arr,axis=1))
print(np.median(arr,axis=1))
print(np.std(arr,axis=1))

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:",np.floor(a))
print("Ceiling:",np.ceil(a))
print("Truncated:",np.trunc(a))
print("Round:",np.round(a))

[[1 2 3]
 [4 5 6]]
[-2.75 -0.25 -3.75]
[-1.5  1.5 -1.5]
[-0.25  3.25  0.75]
[-0.5 -5. ]
[ 1. -4.]
[2.  0.5]
[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]
[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


Q3

In [21]:
arr = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:",np.sort(arr))
print("Indices:",np.argsort(arr))
print("4 smallest:",np.sort(arr)[:4])
print("5 largest:",np.sort(arr)[-5:])


Sorted: [ 10  16  16  52  54  62 453]
Indices: [0 3 4 1 5 2 6]
4 smallest: [10 16 16 52]
5 largest: [ 16  52  54  62 453]


In [22]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers = array[array == array.astype(int)]
print("Integer elements:", integers)
floats = array[array != array.astype(int)]
print("Float elements:", floats)


Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]


Q4